-- Creando tablas
CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK  (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);



-- Creando proyectos 
INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('Creando una App', 1, 'Usando javascript','2020-07-26')

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('Creando una App', 1, 'Usando PHP','2020-07-30')   

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('Creando una App', 1, 'Usando C++','2020-08-10') 

-- Creando Tareas
INSERT INTO tasks (name,done,projectId)
    VALUES ('descargar Vuejs',false,1);

INSERT INTO tasks (name,done,projectId)
    VALUES ('descargar Node',false,1);

INSERT INTO tasks (name,done,projectId)
    VALUES ('Maquetear el backend',false,1);    

INSERT INTO tasks (name,done,projectId)
    VALUES ('Leer documentacion',false,2);

INSERT INTO tasks (name,done,projectId)
    VALUES ('Instalar Codeigniter',false,2);

INSERT INTO tasks (name,done,projectId)
    VALUES ('Maquetear Vistas',false,2);            

INSERT INTO tasks (name,done,projectId)
    VALUES ('Leer documentación',false,3);    